apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-applier-monitoring
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: flux-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
