apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: gitops-demo
        image: wolfgangofner/kubernetesdeploymentdemo:start
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "50Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: gitops-demo
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: gitops-demo
  ports:
    - port: 80
      targetPort: 80

